# LibreChat Configuration
# Generated by Terraform for Azure deployment
# This file enables MCP (Model Context Protocol) support

version: 1.1.3

# Cache configuration
cache: true

# Registration configuration
registration:
  socialLogins: ["github", "google"]
  allowedDomains: ["playful.ai", "strattonstudiogames.com"]

# Interface configuration
interface:
  customWelcome: "Welcome to Playful LibreChat!"
  privacyPolicy:
    externalUrl: ""
    openNewTab: true
  termsOfService:
    externalUrl: ""
    openNewTab: true
%{ if enable_mcp ~}
  modalAcceptance: true
  modalTitle: "Terms of Service for LibreChat"
  modalContent: "MCP ON"
%{ endif ~}
  endpointsMenu: true
  modelSelect: true
  parameters: true
  sidePanel: true
  presets: true

%{ if enable_mcp ~}

# MCP (Model Context Protocol) Servers
mcpServers:
  # amplitude-analytics-instantgarden:
  #   command: npx
  #   args:
  #     - -y
  #     - "@playful-ai-games/amplitude-mcp"
  #     - --amplitude-api-key=$${AMPLITUDE_API_INSTANTGARDEN}
  #     - --amplitude-secret-key=$${AMPLITUDE_SECRET_INSTANTGARDEN}
  #   timeout: 60000        # Increase request timeout to 60 seconds
  #   initTimeout: 60000    # Increase initialization timeout to 60 seconds

  # amplitude-analytics-alphalife:
  #   command: npx
  #   args:
  #     - -y
  #     - "@playful-ai-games/amplitude-mcp"
  #     - --amplitude-api-key=$${AMPLITUDE_API_ALPHALIFE}
  #     - --amplitude-secret-key=$${AMPLITUDE_SECRET_ALPHALIFE}
  #   timeout: 60000        # Increase request timeout to 60 seconds
  #   initTimeout: 60000    # Increase initialization timeout to 60 seconds

  amplitude-official:
    url: https://mcp.amplitude.com/mcp
    type: streamable-http
    requiresOAuth: true
    timeout: 60000
    initTimeout: 60000
    oauth:
      authorizationUrl: "https://auth.amplitude.com/oauth2/auth"
      tokenUrl: "https://auth.amplitude.com/oauth2/token"
      # clientId: "$${AMPLITUDE_OFFICIAL_CLIENT_ID}"
      # clientSecret: "$${AMPLITUDE_OFFICIAL_CLIENT_SECRET}"
      # scope: "$${AMPLITUDE_OFFICIAL_SCOPE}"
      redirectUri: "${librechat_app_url}/api/mcp/amplitude-official/oauth/callback"

  sensortower: 
    command: uvx
    args: 
      - sensortower-mcp
    env:
      SENSOR_TOWER_API_TOKEN: "$${SENSOR_TOWER_API_TOKEN}"


%{ endif ~}



# Azure OpenAI Endpoint Configuration
endpoints:
  azureOpenAI:
    groups:
      - group: "azure-deployments"
        apiKey: "${azure_api_key}"
        instanceName: "${azure_instance}"
        version: "${azure_version}"
        models:
%{ for deployment_name in azure_deployments ~}
          ${deployment_name}:
            deploymentName: ${deployment_name}
%{ endfor ~}

# File configuration
fileConfig:
  endpoints:
    assistants:
      fileLimit: 5
      fileSizeLimit: 10
      totalSizeLimit: 50
      supportedMimeTypes:
        - "image/.*"
        - "application/pdf"
    default:
      totalSizeLimit: 20
    openAI:
      disabled: true
    azureOpenAI:
      disabled: false
    googleVertex:
      disabled: false
    anthropic:
      disabled: false
  serverFileSizeLimit: 100
  avatarSizeLimit: 2

# Rate limiting
rateLimits:
  fileUploads:
    ipMax: 100
    ipWindowInMinutes: 60
    userMax: 50
    userWindowInMinutes: 60
  conversationsImport:
    ipMax: 100
    ipWindowInMinutes: 60
    userMax: 50
    userWindowInMinutes: 60
