# LibreChat Configuration
# Generated by Terraform for Azure deployment
# This file enables MCP (Model Context Protocol) support

version: 1.1.3

# Cache configuration
cache: true

# Registration configuration
registration:
  socialLogins: ["github", "google"]
  allowedDomains: ["playful.ai", "strattonstudiogames.com"]

# Interface configuration
interface:
  customWelcome: "Welcome to Playful LibreChat!"
  privacyPolicy:
    externalUrl: ""
    openNewTab: true
  termsOfService:
    externalUrl: ""
    openNewTab: true
%{ if enable_mcp ~}
  modalAcceptance: true
  modalTitle: "Terms of Service for LibreChat"
  modalContent: "MCP ON"
%{ endif ~}
  endpointsMenu: true
  modelSelect: true
  parameters: true
  sidePanel: true
  presets: true

# Custom endpoints for Azure OpenAI
endpoints:
  custom:
    - name: "Azure OpenAI"
      apiKey: "${azure_api_key}"
      baseURL: "https://${azure_instance}.openai.azure.com/openai/deployments/${azure_deployment}"
      models:
        default: ["gpt-4.1"]
        fetch: false
      titleConvo: true
      titleModel: "gpt-4.1"
      summarize: false
      summaryModel: "gpt-4.1"
      forcePrompt: false
      modelDisplayLabel: "Azure OpenAI"
      dropParams: ["stop", "user", "frequency_penalty", "presence_penalty"]
      headers:
        api-key: "${azure_api_key}"
      params:
        api-version: "${azure_version}"

# Agents configuration (currently disabled - uncomment if needed)
#agents:
#  # Enable agents endpoint
#  enabled: true
#  
#  # Maximum recursion depth for agent actions
#  recursionLimit: 10
#  
#  # Maximum allowed recursion limit that can be set
#  maxRecursionLimit: 10
#  
#  # Enable/disable the agent builder interface
#  disableBuilder: false
#  
#  # Maximum number of citations to display
#  maxCitations: 5
#  
#  # Agent capabilities
#  capabilities:
#    - "webSearch"
#    - "codeInterpreter"

%{ if enable_mcp ~}

# MCP (Model Context Protocol) Servers
mcpServers:
  amplitude-analytics-instantgarden:
    command: npx
    args:
      - -y
      - amplitude-mcp
      - --amplitude-api-key=$${AMPLITUDE_API_INSTANTGARDEN}
      - --amplitude-secret-key=$${AMPLITUDE_SECRET_INSTANTGARDEN}

%{ endif ~}



# File configuration
fileConfig:
  endpoints:
    assistants:
      fileLimit: 5
      fileSizeLimit: 10
      totalSizeLimit: 50
      supportedMimeTypes:
        - "image/.*"
        - "application/pdf"
    default:
      totalSizeLimit: 20
    openAI:
      disabled: true
    azureOpenAI:
      disabled: false
    googleVertex:
      disabled: true
    anthropic:
      disabled: true
  serverFileSizeLimit: 100
  avatarSizeLimit: 2

# Rate limiting
rateLimits:
  fileUploads:
    ipMax: 100
    ipWindowInMinutes: 60
    userMax: 50
    userWindowInMinutes: 60
  conversationsImport:
    ipMax: 100
    ipWindowInMinutes: 60
    userMax: 50
    userWindowInMinutes: 60